### ISSUE TITLE
Create Issue assigned to group

### ISSUE THREAD

**Issue by avierck** [kbsali/php-redmine-api#103]
As far as I can see, so far its not possible to create a ticket and assign it to a group instead of a user via 'assigned_to', is there a way so resolve this, maybe going through the group api? 
Update: Using 'assigned_to_id' and the group id works, so one would only need to look up the group name for the id.

**Comment by kbsali** [comment]
@avierck sorry for the (very) late follow up, can we close this issue then? You seem to have found a work around...
