### ISSUE TITLE
Curl response was a one spaced string

### ISSUE THREAD

**Issue by mrbinr** [kbsali/php-redmine-api#104]
Hi,
in file <strong>lib/Redmine/Client.php</strong> on line 389 there is curl response, and in my case, was an empty string " " and this thrown an exception on line 403 when it tries to instanciate SimpleXMLElement : 

<pre>return new SimpleXMLElement($response);</pre>

I have checked <strong>$contentType</strong> which was <strong>'application/xml'</strong>
In my case it occured when responseCode was 500 ( Project's tracker not defined )

To fix it i have add trim() on curl response, but may there is a better way to do it.

Best regards

pascall

**Comment by kbsali** [comment]
Hi @mrbinr,
If the trim() solution worked for you, it might work for others! :) So go ahead a create PR to get it in! I'd be more than happy to accept it!

**Comment by funivan** [comment]
I think `trim` just remove spaces. You cant init `SimpleXMLElement` with empty string
I see 2 solutions of this:
- If we have empty response from server  init `SimpleXMLElement` with following content
```xml
<errors type="array">
  <error>Empty response from server</error>
</errors>
```

- throw exception

**Comment by mrbinr** [comment]
Hi,
@funivan trim() works because test before SimpleXMLElement init avoid instanciation.
When i've tried it, it works for me...

@kbsali ok, i will do it ...

**Comment by kbsali** [comment]
forgot to close this after merging PR #105...
