### ISSUE TITLE
Updates through API to write a comment fails with status 200 response

### ISSUE THREAD

**Issue by EldrosKandar** [kbsali/php-redmine-api#106]
I'm trying to write a comment in redmine using the following line:

$issuenumber = 12345;
$comment = "api comment";
$client->api('issue')->update($issuenumber,['notes'=>$comment]);

But although the command doesn't fails and send a status 200 response, the response itself is empty, and the only thing changed in the redmine task is time at which it was last updated.

It appears to be a similar issue as documented here: http://www.redmine.org/issues/12496

**Comment by Art4** [comment]
I've investigated in this issue. With Redmine 4.1.1 and php-redmine-api 1.7.0 the request will return a `204 No Content` response. In the issue the `changed at` updated and a new comment was set.

What ever causes this issue in 2015: I think that this has been solved on the Redmine side and was not an issue with this library.
