### ISSUE TITLE
can not create an issue with a custom-field which has a multi_value

### ISSUE THREAD

**Issue by gggeek** [kbsali/php-redmine-api#108]
If I set to a php array the value of a custom attribute, which has been defined as multivalued in redmine, the issue creation call fails

See here for the correct XML to produce in that case: http://www.redmine.org/issues/11952

**Comment by gggeek** [comment]
Sent PR: https://github.com/kbsali/php-redmine-api/pull/109

**Comment by kbsali** [comment]
should be fixed in #87
