### ISSUE TITLE
Set Custom Field on User Creation

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#110]
i have a task to create many users through the rest API. All this Users need to check a Checkbox. So i do this:
```
Array
(
    [login] => peter@klausiloewasfasnf.gov
    [firstname] => Klaus
    [lastname] => Peter
    [mail] => peter@klausiloewasfasnf.gov
    [password] => nqASpKpX
    [cf_10] => 1
)
```

but nothing happens! The user will be created but the custom field will not be set. I do it like your told in the example.php. The ID from this customfield is 10.

Can you help me?

**Comment by Art4** [comment]
Untested:

```php
$client->api('user')->create(array(
    'login' => 'test',
    'firstname' => 'test',
    'lastname' => 'test',
    'mail' => 'test@example.com',
    'custom_fields'  => array(
        array(
            'id'    => 10,
            'name'  => 'CUSTOM_FIELD_NAME',
            'value' => 1,
        ),
    ),
));
```

Your example with `cf_10` is used to list users.

**Comment by Henry31** [comment]
Thanks a Lot! This works nicely! 

sorry it was my fault.
