### ISSUE TITLE
Can't find the right syntax to create a custom_fields when creating a project

### ISSUE THREAD

**Issue by ssimon27** [kbsali/php-redmine-api#111]
Hi.
I'm having an issue when I try to insert a custom_field when creating a project :

![sans titre](https://cloud.githubusercontent.com/assets/10956180/6144599/b6b40456-b1d9-11e4-8d70-0740cab6ad56.png)

Can someone tell me what's wrong with my code please ?
By the way, this is the error I get when I try to create it :

![sans titre](https://cloud.githubusercontent.com/assets/10956180/6144709/aa3a289e-b1da-11e4-92ca-251adc8e59b4.png)

Thanks.

**Comment by Art4** [comment]
Every custom field data must be in a seperate array:

```php
$client->api('project')->create(array(
    //'name', 'description', and so on
    'custom_fields' => array(
        array(
            'id' => 4,
            'name' => 'Service(s)',
            'value' => 'test',
        ),
    ),
));
```

**Comment by ssimon27** [comment]
First of all, thank you for taking the time to answer.
However, I already tried that,

![image](https://cloud.githubusercontent.com/assets/10956180/6147752/fb777458-b1fa-11e4-8628-1ed28a1dcec8.png)

 and it gave me the same error as above.

**Comment by Art4** [comment]
Ok, next try: The value of `tracker_ids` must be an array. Make sure, `$project->getTracker()` returns an array or use `'tracker_ids' => array($project->getTracker()),`

**Comment by ssimon27** [comment]
It's value is an array.
In fact, everything is working, my project is created in redmine, except that it hasn't any custom field filled, and this error appears on my page.
I really don't know what to do now...

**Comment by Art4** [comment]
Ok, I'm running of ideas and cannot test this right now. Maybe someone else could help.

**Comment by Henry31** [comment]
I think it´s the same error i get here #123 !

**Comment by kbsali** [comment]
this duplicates #123 as @Henry31 mentioned.
I'm afraid this is not possible via the API simply because the api does not support custom_field for project (and nor that this php client).
