### ISSUE TITLE
Cannot update issue's done_ratio when the given value is zero

### ISSUE THREAD

**Issue by Halmaethor** [kbsali/php-redmine-api#112]
Hi,

I'm having a problem with updating an issue, the done_ratio doesn't update when I give the value zero. For example, if the current done_ratio is > 0 and I want to "restart" it, I can't.

This is due to the use of array_filter without a proper callback (it just verifies if the values are == false). I'll send a PR do solve this issue.

**Comment by Halmaethor** [comment]
Sent PR: #113

**Comment by kbsali** [comment]
@Halmaethor closing as your PR should have fixed your issue.
