### ISSUE TITLE
getIdByUsername didn´t work

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#115]
Hello,

i wrote a script to create some users in our redmine system automatically. But many times we got an error because the function "getIdByUsername" gives a "False" back. I don´t know why this happend. The Username exist in our Redmine System. Everything seems okay.

``` php
$user_id = $client->api('user')->getIdByUsername($sheetData[$i]['J']);
```

some example for the structure of our usernames:
- test-user@test.de
- test.user@gmail.com
- test@test-website.de

yes we use the e-mail adress also as the username/loginname

Can you help me with this problem? it seems that 70% of our tasks gone wrong because of this error!

**Comment by Henry31** [comment]
okay, i tested a lot more. Now every task failed at this point...

**Comment by Henry31** [comment]
It seems to be a Limit Problem.

```php
 public function listing($forceUpdate = false)
    {
        if (empty($this->users) || $forceUpdate) {
            $this->all();
        }
        $ret = array();
        if (is_array($this->users) && isset($this->users['users'])) {
            foreach ($this->users['users'] as $e) {
                $ret[$e['login']] = (int) $e['id'];
            }
        }

        return $ret;
    }
```

I think the issue is about the limitation with 25 users per default...?

**Comment by spin0us** [comment]
You can add a filter in the search like this
`public function getIdByUsername($username, array $params = [])
    {
        $params['name'] = $username;
        $arr = $this->listing(true, $params);
        if (!isset($arr[$username])) {
            return false;
        }

        return $arr[(string) $username];
    }`

**Comment by kbsali** [comment]
thanks  @spin0us for your solution :+1: ,
@Henry31 if you are ok with this, please close the issue! :)

**Comment by Henry31** [comment]
Hi,

I didn´t work on this topic anymore. But also thanks to @spin0us for this solution. Hopefully, this will help other people :)

So I´m okay with that 👍
