### ISSUE TITLE
Get child issue from the current issue

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#120]
Hello i want to know the child issue from an issue.

Something like that:

```
$client->api('issue')->show(13997, array ('includes' => 'children'));
```

Like documented here: http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Showing-an-issue
(See includes)

Thanks a Lot!

**Comment by adamgieron** [comment]
Try:
`$client->api('issue')->show(xxxxx, array ('include' => 'children')); `

**Comment by Art4** [comment]
As @adamgieron said this can already be done with:

```php
$client->getApi('issue')->show($issueId, ['include' => 'children']);
// or
$client->getApi('issue')->show($issueId, ['include' => ['children']]);
```
