### ISSUE TITLE
Access to an issues attachment via issueId

### ISSUE THREAD

**Issue by lydianFolk** [kbsali/php-redmine-api#121]
Hello and thank you for sharing this library.

I wonder, if I have access to an issues attachment, if only the issueId is known. I dumped like this: 

var_dump($client->api('issue')->show($issueId));

There are a lot of issue related informations available, but nothing like an attachmentId or an array of several attachmentIds. I really stuck at this point. Does any method cover this aspect:

GET /issues/:id.:format?include=attachments

Thanks in advance

**Comment by ferdynator** [comment]
Try `$client->api('issue')->show($issueId, array('include' => array('attachments')));`

See [Api/Issue,php#L49](https://github.com/kbsali/php-redmine-api/blob/master/lib/Redmine/Api/Issue.php#L49) in the comments.

**Comment by kbsali** [comment]
@lydianFolk could you confirm @ferdynator 's solution works ok for you?
If so, please close the issue.

Thx.

**Comment by lydianFolk** [comment]
Thank you, ferdynator. In fact I havn't seen this part of the api description. Shame on me. I tried your suggestion. Unfortunately this does not succeed too. It provides issue related data but nothing about attachments. same, when using ```$client->api('issue')->show($issueId, array('attachments')))```
I wonder how to get this working.

Kind regards

**Comment by lydianFolk** [comment]
got access via curl. thx anyway
