### ISSUE TITLE
Can´t set a custom field on update

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#123]
I try to update a project through the php redmine api.
```php
$client->api('project')->update($project_id, array(
					'name' => 'diffrent name',
					'custom_fields'  => array(
						array(
								'id'    => 25,
								'name'  => 'Team',
								'value' => 'Team 1',
						),
					),
			);
```
the name will be update but the custom field won´t be set. I only get this error:
```
Warning: SimpleXMLElement::addChild() expects parameter 2 to be string, array given in C:\xampp\htdocs\Projekt_Automat\php-redmine-api\vendor\kbsali\redmine-api\lib\Redmine\Api\SimpleXMLElement.php on line 23
```

**Comment by kbsali** [comment]
@Henry31 i believe the project api does not support custom_fields (and the client either, that's why you get the error...).

Please close the issue unless you do find info about custom_field support for the porject api.

Thanks.

**Comment by kbsali** [comment]
confirmed.

re-open if you find more info.
