### ISSUE TITLE
Search issues by multiple values (i.e. status_id or tracker_id)

### ISSUE THREAD

**Issue by ghost** [kbsali/php-redmine-api#127]
I tried `/issues.xml?status_id=8&status_id=10` but it doesn't work, it seems that search is performed against one value only (same thing for tracker_id)

I found on StackOverflow this answer http://stackoverflow.com/a/18358659 about an undocumented way of calling issue API with multiple values, like this `/issues.json?project_id=154&f[]=status_id&op[status_id]==&v[status_id][]=10&v[status_id][]=8&sort=updated_on` 

by the way, such query is visible from standard redmine issue query UI, and it works performing query in Postman too

Could it be possible to use this undocumented syntax in php-redmine-api too?
Does it make sense?

thanks

**Comment by Philosoft** [comment]
:+1:  it'd be handy.

**Comment by kbsali** [comment]
that looks interesting @marcofrattola ,
but i failed understand the logic of the arguments list of the example you found on stackoverflow?

It looks like this has been asked for a long time ago and Redmine's lead dev had a proposal : http://www.redmine.org/issues/10828
I'm not sure if it has been added to the api though... (would you mind checking? status_id=8|10) ?

**Comment by marcofrattola** [comment]
@kbsali I checked, it seems working this syntax too, thanks. Do you consider port this syntax into php-redmine-api ...?

**Comment by roidayan** [comment]
Hi,

From my testing using the | separator works for me with an online redmine hosting and demo.redmine.org so it seems the patch is applied.

**Comment by Art4** [comment]
I've tested this feature with Redmine 4.1.1:

```php
$client->getApi('issue')->all([
    'project_id' => '6',
    'status_id' => '5|6',
]);
```

Worked like expected. @kbsali This can be closed.
