### ISSUE TITLE
user_ids property not available for membership create method.

### ISSUE THREAD

**Issue by agileware** [kbsali/php-redmine-api#148]
Hi,

Just to let you know that the user_ids property is not available for the membership create method in the Redmine API. See http://www.redmine.org/projects/redmine/wiki/Rest_Memberships#POST

So if you try to use the php-redmine-api to add a membership for a group using the user_ids property, this will fail and Redmine will return a 500 HTTP error.

The solution is to just use the user_id property instead, as this works for both users and group memberships.

Best wishes!

**Comment by kbsali** [comment]
thx @agileware,
sorry for the late answer. The latest release should fix the issue.
