### ISSUE TITLE
Get the last Ticket with status id 5

### ISSUE THREAD

**Issue by Samhamsam** [kbsali/php-redmine-api#150]
Hello Guys,

thank you so much for this great work!
I have the following question: 
Is there a way to get the last Ticket that was closed, without to make a big loop and compare every date.

I have tried this with the following code but it does not work. It gives me just the Ticket with the highest id that was closed.
```
$client->api('issue')->all(array(
	'sort:desc' => 'closed_on',
	'status_id' => '5',
	'limit' => 1,
));
```

Is there a better way to do this?

Thanks

**Comment by Art4** [comment]
I think the `:desc` must append to the value:

```php
$client->api('issue')->all(array(
    'sort' => 'closed_on:desc',
    'status_id' => '5',
    'limit' => 1,
));
```

**Comment by Samhamsam** [comment]
Thanks you! Now it works perfectly.
Another question: Can i return just the Ticket id's? 
```
$ticket-ids = $client->api('issue')->all(array(
	'sort' => 'closed_on:desc',
	'status_id' => '5',
	'limit' => 10000,
        //give me just Ticket-ID's
));
```
So that in the variable $ticket-ids are just numbers. Like: 1,2,3,4,5,etc

**Comment by Art4** [comment]
That is imho not possible.

**Comment by Samhamsam** [comment]
Ok. Thank you!

**Comment by kbsali** [comment]
Thanks @Art4 ! ;)
