### ISSUE TITLE
Unable to create new issue with PHP 7

### ISSUE THREAD

**Issue by mpreitz** [kbsali/php-redmine-api#155]
First of all: thank you for your work! 

My Environment:
Redmine version - 3.2.0.stable.14976
php-redmine-api - master-branch

I can connect to my redmine instance, can read the users, etc.
But if I wan't to create a new issue with the following code

> require 'redmine/lib/autoload.php';
>         $this->_rm = new Redmine\Client(
>             'https://TARGET-URL',
>             'API_KEY'
>         );
>         $this->_rm->setCheckSslCertificate(true);
>         $this->_rm->api('issue')->create([
>             'project_id'  => 'mdrza-2015',
>             'subject'     => 'API-Test',
>             'description' => 'a long description blablabla',
>             'assigned_to_id' => 4
>         ]);

nothing happens.
Redmine production log says:

> Started POST "/issues.xml" for XXX.XXX.XXX.XXX at 2016-02-04 12:40:10 +0100
> 
> ActionDispatch::ParamsParser::ParseError (#<REXML::ParseException: malformed XML: missing tag start
> Line: 2
> Position: 210
> Last 80 unconsumed characters:
> <0>API-Test</0></subject><description><0>a long description blablabla</0></descri>
> /usr/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:372:in `pull_event'
> /usr/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
> /usr/lib/ruby/2.0.0/rexml/parsers/treeparser.rb:22:in `parse'

What am I doing wrong?

**Comment by belug23** [comment]
Since Redmine 3 the project_id needs to be the numeric id of the project.

**Comment by kbsali** [comment]
thanks for the input @belug23 .
@mpreitz did that help? Can we close that issue?

**Comment by duxthefux** [comment]
I also can't create a new issue:
$ticket = $redmine->getApi()->issue->create([
            'project_id'  => $request->project_id,
            'subject'     => $request->summary,
            'description' => $request->description,
            'assigned_to' => $request->user_id,
        ]);

it only works if I do: (Issue.php: Line 148)
 #return $this->post('/issues.xml', $xml->asXML());
$json = json_encode(array('issue' => $params));
return $this->post('/issues.json', $json);

instead of
return $this->post('/issues.xml', $xml->asXML());
// $json = json_encode(array('issue' => $params));
// return $this->post('/issues.json', $json);

what could be the problem with XML?

**Comment by belug23** [comment]
@duxthefux could you please post the json and xml content and the error response, without the content it's almost imposible to understand your problem.

**Comment by duxthefux** [comment]
@belug23:
I assume you are looking for something like this:
XML-Variant:
Started POST "/issues.xml" for 80.108.208.122 at 2016-03-17 14:12:31 +0000
Processing by IssuesController#create as XML
  Current user: admin (id=1)
Filter chain halted as :find_project rendered or redirected
Completed 404 Not Found in 10ms (ActiveRecord: 0.8ms)

JSON-Variant:
Started POST "/issues.json" for 80.108.208.122 at 2016-03-17 14:03:05 +0000
Processing by IssuesController#create as JSON
  Parameters: {"issue"=>{"subject"=>"testest", "description"=>"afdfasd", "project_id"=>"4"}}
  Current user: admin (id=1)
  Rendered mailer/_issue.text.erb (7.8ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (8.3ms)
  Rendered mailer/_issue.html.erb (1.6ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (1.9ms)
  Rendered issues/show.api.rsb (1.8ms)
Completed 201 Created in 1525ms (Views: 2.0ms | ActiveRecord: 461.2ms)


It looks like no parameters are added to the XML - POST.

I this was not the information you asked, please tell me :-)

**Comment by belug23** [comment]
@duxthefux More something like the result of:
    `var_dump($this->post('/issues.xml', $xml->asXML()));`

**Comment by duxthefux** [comment]
that's easy

"false"

**Comment by belug23** [comment]
@duxthefux  Sorry my mistake please use :
`var_dump($xml->asXML());`

**Comment by duxthefux** [comment]
@belug23 

<?xml version="1.0"?>\n
<issue><subject>testest</subject><description>afdfasdasd</description><project_id>4</project_id></issue>\n

**Comment by belug23** [comment]
@duxthefux Is that the source or the html rendering? If it's the source there's something wrong with your xml encoder if it's the rendering use the next line to make it printable properly:

`var_dump(htmlentities ($xml->asXML()));`

**Comment by duxthefux** [comment]
@belug23 
that's the output of `var_dump(htmlentities ($xml->asXML()));`
`string(191) "<?xml version="1.0"?> <issue><subject>testest</subject><description>afdfasdasd</description><project_id>4</project_id></issue> "`

**Comment by belug23** [comment]
@duxthefux from what I see here, everything is ok from the side of php-redmine-api... looks like a problem on the redmine side not accepting your xml properly.

From here I cannot help anymore and is outside the the subject of this issue.

You should look for help on the redmine issue tracker http://www.redmine.org/projects/redmine/issues 

You should use the data I ask for the XML, the redmine log and the last print of the content of your xml if you create an issue there. You should include your ruby and rails versions.

Sorry I can't help you.

**Comment by duxthefux** [comment]
oh man, too bad...I didn't find anything on the internet by now...do have any hint which could help me? missing libraries or whatever?

**Comment by belug23** [comment]
I'm not really knowledgeable in ruby and rails, I really cannot help you, except that I don't understand why you don't have the parameters in the log like in mine :

> Started POST "/issues.xml" for 127.0.0.1 at 2016-03-14 15:01:06 -0400
> Processing by IssuesController#create as XML
>   Parameters: {"issue"=>{"subject"=>"test", "project_id"=>"2", "tracker_id"=>"2",  "description"=>"test"}}
>  Current user: belug (id=6)

May you could start by why rails cannot read xml... if you have access to a linux you could try  :

`$ curl -v -H "Content-Type: application/xml" -X POST --data "@test.xml"  -u test:testpass https://example.com/issues.xml`

with this test.xml file :

`<?xml version="1.0" encoding="ISO-8859-1" ?>
<issue>
  <subject>test</subject>
  <project_id>4</project_id>
  <description>test</description>
</issue>`

**Comment by duxthefux** [comment]
the curl gives me a 404 error...

```
* upload completely sent off: 144 out of 144 bytes
< HTTP/1.1 404 Not Found
< Date: Thu, 17 Mar 2016 16:03:04 GMT
< Server: Apache/2.4.12 (Ubuntu)
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache
< X-Request-Id: 287f7619-2948-4248-9f18-9e7052d415a2
< X-Runtime: 0.017543
< X-Powered-By: Phusion Passenger 4.0.53
< Status: 404 Not Found
< Transfer-Encoding: chunked
< Content-Type: application/xml
```

**Comment by belug23** [comment]
So now it's really on the redmine side, did you enable the REST api in admin?

**Comment by mpreitz** [comment]
@belug23 @kbsali Thanks for the advice, but changing the project_id to the numeric id didn't solved the problem.
In addition the log states:

> malformed XML: missing tag start
Line: 2
Position: 195
Last 80 unconsumed characters:
<0>API-Test</0></subject><description><0>a long description blablabla</0></descri
Line: 2
Position: 195
Last 80 unconsumed characters:
<0>API-Test</0></subject><description><0>a long description blablabla</0></descri):

Inspired by @duxthefux I've "dumped" the XML by adding `var_dump($xml->asXML());` in Line 147 of Remine/Api/Issue.php.
The Output:
> string(195) " <0>API-Test<0>a long description blablabla244 "

The Sourceview:
`<?xml version="1.0"?>
<issue><subject><0>API-Test</0></subject><description><0>a long description blablabla</0></description><project_id>24</project_id><assigned_to_id>4</assigned_to_id></issue>`
The problem is visible here. subject and description contains illegel tags <0></0>. But at the moment I've no clue where this tags are comming from.

I've also changed the submission to JSON by changing the lines 148-150 in Issue.php to
`        //return $this->post('/issues.xml', $xml->asXML());
        $json = json_encode(array('issue' => $params));
        return $this->post('/issues.json', $json);`
This way the ticket is created.

**Comment by mpreitz** [comment]
Did a bit more testing.
Ran the following code in a test file:
`$data = array(
    'project_id'  => 24,
    'subject' => 'APITest',
    'description' => 'a long description blablabla',
    'assigned_to_id' => 4
);
$ret = $rm->api('issue')->create($data);


$test = new SimpleXMLElement('<?xml version="1.0"?><issue></issue>');
foreach ($data as $k => $v) {
    $test->addChild($k, $v);
}
var_dump($test->asXML());`

php-redmine-api produced the following XML (var_dump in issue.php):

` <?xml version="1.0"?>
<issue><project_id>24</project_id><subject><0>APITest</0></subject><description><0>a long description blablabla</0></description><assigned_to_id>4</assigned_to_id></issue>`

The direct test with SimpleXMLElement produced:
`<?xml version="1.0"?>
<issue><project_id>24</project_id><subject>APITest</subject><description>a long description blablabla</description><assigned_to_id>4</assigned_to_id></issue>`

Every string in the api is wrapped with the "zero-tags" which produces invalid XML.

**Comment by duxthefux** [comment]
I don't think we have the same problem...i ended up upgrading redmine to the latest version and now it works as expected...i used the version 2.5 which is available in apt-get.

**Comment by belug23** [comment]
Good @duxthefux I'm happy you resolved your problem. 

@mpreitz I cannot see why the API would do something that strange from what I can see in the master branch,

**Comment by mpreitz** [comment]
@belug23 I'm also confused. Because of the test without calling the API I would think that the problem is not located in the environment. Because then the output should also be invalid. I've also made diffenrent tests inside Issue.php and placed the generation of XML on various spots to be sure that there is no problem inside sanitizing or "cleanParams". But always the XML that is generated by the API has this Zero-Tags inside. 
In addition I've tested on a different machine. Local: Mac OS X, Remote: Ubuntu 14.04. Same result. So I think it's definitely not a problem with environment.

**Comment by mpreitz** [comment]
OK, found one more hint:
The problem only occurs on PHP7. Tried with 5.6 and XML is generated fine. 
Now searching for the different between the two versions.

**Comment by belug23** [comment]
@mpreitz that is wierd and I still cannot understand why would the generation would change in php7

**Comment by mpreitz** [comment]
@belug23 The really weird thing is: why is the "broken" XML only generated inside the class.
To make sure it is no problem with the code of the API I've added the following code to line 121 of Issue.php:
`$xml = new SimpleXMLElement('<?xml version="1.0"?><issue></issue>');
 $xml->addChild('test', 'APITEST');
var_dump($xml->asXML());`
So no code from the API itself is used, but guess what: the output is invalid!
I think this must be a problem of PHP7 itself.

**Comment by mpreitz** [comment]
@belug23 @kbsali The problem is not PHP7. The problem occurs in /lib/Reminde/Api/SimpleXMLElement.php. I havent found the problem yet, but the "Zero"-Tag is added inside the inherited class.

**Comment by mpreitz** [comment]
@belug23 @kbsali Got it!
In PHP7 the property overloading seems so set the type of the new property to string. But for correct function an numeric value is needed.

Chaging /lib/Redmine/Api/SimpleXMLElement.php Line 21 from
`$node->{0} = $text;`

to
`$node->{intval(0)} = $text;`

will fix this issue and wellformed XML is generated.

**Comment by kbsali** [comment]
awesome @mpreitz ! Do you want to submit a PR for fixing this?

**Comment by mpreitz** [comment]
No problem. But give me a day or two to check it in PHP 5.X so this change doesn't break backward compability.

**Comment by mpreitz** [comment]
@kbsali PR created: #160  . Hopefully everything is fine. It's my first one. ;-)
If everything is fine this issue can be closed.

**Comment by adamhesim** [comment]
Hello,
I got the exact same issue but it doesn't seems to come from your code : even with the proper command-line curl, i got this _'Filter chain halted as :find_project rendered or redirected, 404 ...'_.
Could you please have a look to my curl and tell me if something is wrong (if not, i guess the bug is on my Redmine instance (Debian Jessie package v3.0) ?

`curl -X POST -d @test.xml -o test --header "Content-Type:application/xml" --header "X-Redmine-API-Key: mykey" http://redmine.myhost.com/issues.xml`

and the test.xml file (this is what is send by the API) : 

`<?xml version="1.0"?><issue><project_id>2</project_id><subject>test</subject><description>test</description></issue>`

Same thing if I change the project_id integer to identifier. User is admin, member of the project, ...
I really can't figure out what I am missing. Thank you in advance for your help.
