### ISSUE TITLE
Change in issue creation from API with redmine 3.x?

### ISSUE THREAD

**Issue by vmmello** [kbsali/php-redmine-api#163]
Hi,

We've been doing issue creation with php-redmine-api and redmine 2.6.x without any issue.

Then we've tried using the same code with redmine 3.2.x and issue creation stopped working when specifying the project_id with the alias name of the project. With 3.2.x it works only if we specify the numeric project_id, otherwise it returns error 500 with:

```
[2016-06-08T14:12:42.971342 #25429] FATAL -- : 
NoMethodError (undefined method `assignable_users' for nil:NilClass):
  app/models/issue.rb:823:in `assignable_users'
  app/models/issue.rb:503:in `safe_attributes='
  app/controllers/issues_controller.rb:439:in `build_new_issue_from_params'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I checked redmine changelogs for 3.0.x, 3.1.x and 3.2.x series and didn't find any mention about that API change. I also disabled all plugins to be sure that it was not a plugin causing it.

Anyway, this is a redmine issue, not a php-redmine-api, I'm just curious that I didn't find other mentions to this problem on my Google searches.

If anyone else is using it successfully with redmine 3.2.x I'd like to know too.

Thanks in advance.

**Comment by smoench** [comment]
@vmmello this has been fixed http://www.redmine.org/issues/23766 (redmine 3.3.1)

**Comment by vmmello** [comment]
@smoench thanks for letting me know!
