### ISSUE TITLE
Losing bytes when downloading files

### ISSUE THREAD

**Issue by denkuz08** [kbsali/php-redmine-api#166]
I'm losing bytes when trying to download file content.
`$attachmenContent = $redmineApi->api('attachment')->download($attachmentId);`
The problem is in line #620 of Client.php
`$response = trim(curl_exec($curl));`
just change it to
`$response = curl_exec($curl);`

**Comment by kbsali** [comment]
@denkuz08 don't be shy : open a PR! :+1: :)

**Comment by kbsali** [comment]
(i could do it myself now that you gave us the hint, but you would not appear as contributor!)
