### ISSUE TITLE
$client->api('issue')->addNoteToIssue() don't return any json or xml response.

### ISSUE THREAD

**Issue by kiserbd** [kbsali/php-redmine-api#168]
Hi there,

$client->api('issue')->addNoteToIssue() on v1.5.9 don't return any json or xml response rather return false after successful add note to the issue. I don't know if i'm doing something wrong or it's a bug!

Thanks.

**Comment by kbsali** [comment]
hi @kiserbd,

sorry for getting back to you so late!
I've checked the code and it returns whatever Redmine API returns... so i'm afraid this is on Redmine's side.
Which version of Redmine are you running?

Thanks
