### ISSUE TITLE
Not possible to set own Curl Options

### ISSUE THREAD

**Issue by mpreitz** [kbsali/php-redmine-api#169]
I've to use this lib behind a proxy. So it's necessary to set CURLOPT_PROXY.
Tried this directly after initialisation.
```php
$rm = new Redmine\Client(
    $redmine['url'],
    $redmine['apikey']
);
$rm->setCurlOption(
    CURLOPT_PROXY, 
    'PROXYURL:PORT'
);
```
But this didn't work.

Looked into Client.php and found this at Line 497:
```php
public function prepareRequest($path, $method = 'GET', $data = '')
    {
        $this->responseCode = null;
        $this->curlOptions = array();
        $curl = curl_init();
```
All Options are cleared when preparing a request (Line 500).
This code was commited in 26e372ddd7b0c9a9fde30d19d47a190ab6eaf996

How can I set needed Curl-Options now?

**Comment by kbsali** [comment]
hi @mpreitz,

could you please test the latest version i've released which should fix this issue.

Thanks
