### ISSUE TITLE
Not possible to set custom_fields when creating projects

### ISSUE THREAD

**Issue by ArnieX** [kbsali/php-redmine-api#170]
Hi,

please fix **project creation script** that it will accept and fill custom fields too. My colleague has fixed it in 1.5.1 version with this code:

```
public function create(array $params = array())
    {
        $defaults = array(
            'name'        => null,
            'identifier'  => null,
            'description' => null,
        );

        $params = array_filter(
            array_merge($defaults, $params),
            array($this, 'isNotNull')
        );

        if(
            !isset($params['name'])
         || !isset($params['identifier'])
        ) {
            throw new \Exception('Missing mandatory parameters');
        }

        $xml = new SimpleXMLElement('<?xml version="1.0"?><project></project>');
        foreach ($params as $k => $v) {
            if ('custom_fields' == $k && is_array($v)) {
                $this->attachCustomFieldXML($xml, $v);
            }
            elseif ('tracker_ids' == $k && is_array($v)) {
                $trackers = $xml->addChild('tracker_ids', '');
                $trackers->addAttribute('type', 'array');
                foreach ($v as $id) {
                    $trackers->addChild('tracker', $id);
                }
            } else {
                $xml->addChild($k, $v);
            }
        }

        return $this->post('/projects.xml', $xml->asXML());
    }
```

But if I want to update to 1.5.9 it is still not working, please fix it if possible. Because in 1.5.1 I have difficulties with custom_fields on time entries instead, which is working in 1.5.9.

Thanks in advance.

**Comment by kbsali** [comment]
@ArnieX please check the latest version i've just released and let me know if your issue is fixed.

thanks

**Comment by ArnieX** [comment]
Hi,

it does indeed fix this particular issue but isn't working properly when I want to assign project to the user immediately after creating it. This was working with 1.5.1 release. When the project is created I can then assign the project with assign script which assign it by project_id. For assigning it after creating I use identifier like this:

  ```
            $allpjids = $client->api('project')->all(array('limit' => 999));
			
			foreach ( $allpjids["projects"] as $project ) {
				
				if ( $project["identifier"] == $identifier ) {
					
					$client->api('membership')->create($project["id"], array(
						'role_ids' => array('id' => REPORTER),
						'user_id' => $userid
					));
	
							
					log_me($userlogin." - Assigned project id ".$project["id"]);
					
				}
								
			}

```
This is because I do not know the project ID yet. If it was returned when project is created it would be easier and less prone to errors. Any idea why this is not working after your fix?

Thank you for your time,

Martin

**Comment by kbsali** [comment]
Hi @ArnieX ,

unfortunately if the id is not returned by the function, it simply means that the API does not return it! :/
So, yet again, this is most probably related to Redmine itself.

**Comment by ArnieX** [comment]
Hi @kbsali,

that is something I'm not questioning. The problem is that even-thought now it is possible to create project with custom fields it fails somewhere else, likely in the function I shared which worked with 1.5.1 after the fix from my colleague. I will find exactly where it fails and let you know if it is related to your library or not.

BR,

Martin

**Comment by kbsali** [comment]
perfect, thanks
