### ISSUE TITLE
Unable to load all time_entry with combination of spent_on and user_id

### ISSUE THREAD

**Issue by ArnieX** [kbsali/php-redmine-api#171]
Hi,

it is not possible to combine **spent_on** parameter and **user_id** parameter in:

`$client->api('time_entry')->all(array( 'spent_on' => '2016-9-9' ,'user_id' => 9 ,'limit' => 100 ));`

it will ignore **user_id** parameter and do the rest only.

Thank you in advance for possible fix.

**Comment by kbsali** [comment]
Hi @ArnieX
unfortunately it is most probably an issue on Redmine' side,
Any parameter you pass to the all() method will be used to query the API.

**Comment by ArnieX** [comment]
Hi @kbsali,

thanks. Strange is that when using UI it is possible to combine these two filters and on API it isn't possible but it could very well be issue on Redmine's side, I wouldn't be surprised ;)

BR,

Martin
