### ISSUE TITLE
retrieveAll without any $params set hits limit

### ISSUE THREAD

**Issue by rogermartensson** [kbsali/php-redmine-api#172]
I'm using a plugin (redissue) that uses Project::getIdByname() to retrieve a Id on a project in Redmine.
But I am hitting a limit on redmine since I have many projects. This limit seems to be 25 entries.

getIdByName() calls listing(). Listing() calls all() if forced or if $this->projects doesn't exists.
all() calls AbstractApi::retrieveAll() with $params set to an empty array when called from listing().
This make retrieveAll() to a get() which seems to retrieve the limit of 25 entries.

If I in all() insert a line like:
`$params['limit']=300;`

Then it seems to work. Not that it uses the supplied limit but skips running the single get() in the beginning of the retrieveAll() function.

**Comment by algorys** [comment]
@rogermartensson I came across your ticket by chance :wink: 

I think it concerns rather the plugin `redissue` cause it's not `php-redmine-api` blame.

**Comment by rogermartensson** [comment]
I'm closing my issue since it's too old.
