### ISSUE TITLE
prepareRequest does not clear curl method and argument options between calls, leading to strange errors on next request

### ISSUE THREAD

**Issue by danb1974** [kbsali/php-redmine-api#182]
Some curl options that are only set for certain types of requests, are not cleared on next request, leading to various strange errors. For example after a PUT, the next GET will use PUT as protocol and pass previous request data.

A quick fix is attached, just to get an ideea of the issue.

[Client.php.diff.txt](https://github.com/kbsali/php-redmine-api/files/585389/Client.php.diff.txt)

**Comment by kbsali** [comment]
hi @danb1974 ,

thanks for reporting the issue (which has been reported by another user last week!).
And thanks for the patch! how about opening a PR instead?

thanks

**Comment by kbsali** [comment]
fixed
