### ISSUE TITLE
Notice: Array to string conversion on create issue relation

### ISSUE THREAD

**Issue by akvamarion** [kbsali/php-redmine-api#185]
$client->issue_relation->create(
                2,
                [
                    'issue_to_id' => 1
                ]
            );

error: Notice: Array to string conversion  (Client.php line 573 )

**Comment by parmar84** [comment]
I think #197 PR should fix this (after I've fixed the tests!)

**Comment by Art4** [comment]
I can confirm that this issue is fixed and can be closed.
