### ISSUE TITLE
Is is possible to add watchers to an existing issue?

### ISSUE THREAD

**Issue by JanisE** [kbsali/php-redmine-api#186]
Watchers are added all right to a new issue upon its creation (`$client->issue->create`), but no watchers get added if I try the same with `$client->issue->update`. Is this a restriction of php-redmine-api or the Redmine API itself?

**Comment by kbsali** [comment]
according to the doc, it seems like you can indeed only add watchers on new issues  : http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Updating-an-issue

**Comment by JanisE** [comment]
Thank you for the pointer! Although, the doc seems to be a bit vague on the issue as they are using a "..." in the list of supported issue parameters for update (not so for create). :)
