### ISSUE TITLE
IssueRelation does not work?

### ISSUE THREAD

**Issue by Sohorev** [kbsali/php-redmine-api#187]
```
$result = $client->issue_relation->create($newIssueId, array(
    'issue_to_id' => $oldIssueId
));
```

PHP Notice:  Array to string conversion in /home/sohorev/workspace/redmine/vendor/kbsali/redmine-api/lib/Redmine/Client.php on line 573

Notice: Array to string conversion in /home/sohorev/workspace/redmine/vendor/kbsali/redmine-api/lib/Redmine/Client.php on line 573

**Comment by Art4** [comment]
In https://github.com/kbsali/php-redmine-api/blob/master/lib/Redmine/Api/IssueRelation.php#L86 `$params` is an array, but it must be a (JSON) string.

Can you please test if this works:

```diff
-        $params = array('relation' => $params);
+        $params = json_encode(array('relation' => $params));
```

**Comment by Sohorev** [comment]
It work normally without php notice, result ok:

```
Array
(
    [relation] => Array
        (
            [issue_id] => 88634
            [id] => 4870
            [issue_to_id] => 71548
            [relation_type] => relates
        )

)


```

**Comment by Sohorev** [comment]
thankyou!

**Comment by Art4** [comment]
You're welcome. It would be great if you would open a pull request for this fix.

**Comment by Sohorev** [comment]
https://github.com/kbsali/php-redmine-api/pull/189
