### ISSUE TITLE
time_entry does not use the passed parameters

### ISSUE THREAD

**Issue by Sohorev** [kbsali/php-redmine-api#188]
```
$params = array(
    'issue_id' => 70452,
//    'user_id' => 7,
);
$times = $client->time_entry->all($params);
```
$times contains absolutely all times of all projects ([limit] => 25, [total_count] => 14921)

**Comment by Art4** [comment]
I can not reproduce this with Redmine 4.1.1 The response has the correct `total_count` and `time_entries`. 

I assume that this was an issue with Redmine but not with php-redmine-api. @kbsali This can be closed.
