### ISSUE TITLE
Custom host in curl header

### ISSUE THREAD

**Issue by Detzler** [kbsali/php-redmine-api#190]
Hi,

it's not possible to set a custom Host in Header via:

```
$redmine = new Redmine\Client('https://127.0.0.1', '....');
$redmine->setCurlOption(CURLOPT_HTTPHEADER, array("Host: myhost.net"));
```

By the way. it's not possible to set any other custom curl headers like this way coz they are overriden in Client::prepareRequest

**Comment by kbsali** [comment]
i have added a setCustomHost() method,
please give it a try.
