### ISSUE TITLE
Create/Update Issue with a multiselect custom_field

### ISSUE THREAD

**Issue by Pilgrim-86** [kbsali/php-redmine-api#193]
Hello,
I would like to now if it's possible to create an issue or update one, where one of the custom_fields is a multiselect field. The problem is that when I try to create an issue with this multiselect custom_field, the ticket is being created but the value of this field is still empty.
Does somebody now how to pass the value of this field to the create method from Issue class?
Thanks for helping me.

**Comment by popnikos** [comment]
May be you can take a look into those methods 
Redmine\Api\Issue.php for method `buildXML`
```foreach ($params as $k => $v) {
            if ('custom_fields' === $k && is_array($v)) {
                $this->attachCustomFieldXML($xml, $v);
            } elseif ('watcher_user_ids' === $k && is_array($v)) {
```
Redmine\Api\AbstractApi.php and `addCustomFields`
```
if (is_array($field['value'])) {
                $_field->addAttribute('multiple', 'true');
                $_values = $_field->addChild('value');
                $_values->addAttribute('type', 'array');
                foreach ($field['value'] as $val) {
                    $_values->addChild('value', $val);
                }
            } else {
```

**Comment by Art4** [comment]
Assuming I have 3 custom_fields for an issue: `foo`, `bar` and `baz`
You can set or update the custom fields of an issue like this:

```php
$php->getApi('issue')->update($issueId, [
    'custom_fields' => [
        [
            'id' => 8, // id of the custom field
            'value' => ['bar', `baz`],
        ],
    ],
]);
```
This will set the 'bar' and `baz` fields. Every other field will be removed/deselected.
