### ISSUE TITLE
adding an attachment to a wiki page

### ISSUE THREAD

**Issue by delatbabel** [kbsali/php-redmine-api#198]
Is it possible via this library to add an attachment to a wiki page?

I have looked through the functions in Wiki.php and there isn't an equivalent to adding an attachment to an issue.  Also the Redmine REST API documentation only gives an example of doing it directly via JSON but this library uses the XML not JSON API.

I have tried expanding the Wiki.php create() function but nothing I try seems to work.

**Comment by Art4** [comment]
Please see the Redmine docs for more details: https://www.redmine.org/projects/redmine/wiki/Rest_WikiPages#Attaching-files

Files have to be upload first and will return a token. This token must then be set to the wiki update method.

```php
$filepath = realpath('/path/to/file');

$return = $client->getApi('attachment')->upload($filepath, ['filename' => 'testfile.txt']);

$filetoken = json_decode($return, true);
// var_dump($filetoken);
// array(1) {
//   ["upload"]=>
//   array(2) {
//     ["id"]=>
//     int(14)
//     ["token"]=>
//     string(67) "14.7b962f8af22e26802b87abfa0b07b21dbd03b984ec8d6888dabd3f69cff162f8"
//   }
// }

// Now we can link the file to a wiki site
$return = $client->getApi('wiki')->update(6, 'Wiki', [
    'text' => 'updated wiki text',
    'uploads' => [
        $filetoken['upload'],
    ],
]);
```
