### ISSUE TITLE
Return all closed tasks of the day

### ISSUE THREAD

**Issue by livioweb** [kbsali/php-redmine-api#204]
I'm having trouble doing this query
```
 $params = [
            'limit' => 1,
            'status_id' => 'close',
            'assigned_to_id'=>16,
            'update_on' => '2017.05.23'
        ];
```

Never returns closed tasks only for the day, always returns all closed

        `http://localhost/issues.json?limit=1&assigned_to_id=16&status_id=5&updated_on=2017-05-23`

So in redmine itself it works, but in this code it does not

Can you help me?

**Comment by kbsali** [comment]
@livioweb found your own answer? :)

**Comment by livioweb** [comment]
yes man, 
```
 $params = [
            'limit' => 1,
            'status_id' => 'close',
            'assigned_to_id'=>16,
            **'update_on' => '2017.05.23' // The correct is [updated_on]**
        ];
```

**Comment by kbsali** [comment]
:+1:
