### ISSUE TITLE
Can we throw an exception if the request goes wrong?

### ISSUE THREAD

**Issue by amenk** [kbsali/php-redmine-api#215]
https://github.com/kbsali/php-redmine-api/blob/master/lib/Redmine/Client.php#L640

**Comment by emilianosce** [comment]
We can use the lastCallFailed() method to check if the request went right or wrong, I use it when creating a project or an issue. Its syntax should be something like this, for example in creating a project:
```
if($client->project->lastCallFailed()){
    echo "error"; 
}
else{
    echo "the request was executed succesfully";
   }
```
Hope it works!

**Comment by Art4** [comment]
With v1.7.0 there is a new `Psr18Client`. This client uses any [PSR-18](https://www.php-fig.org/psr/psr-18/) compatible client where Exceptions will thrown if the request fails. Please note that "response status codes in the 400 and 500 range MUST NOT cause an exception and MUST be returned to the Calling Library as normal." You have to check for 400 and 500 status code in your code.

```php
$guzzle = new \GuzzleHttp\Client();
$psr17Factory = new \GuzzleHttp\Psr7\HttpFactory();

$client = new \Redmine\Client\Psr18Client(
    $guzzle,
    $psr17Factory,
    $psr17Factory,
    'http://redmine.example.com',
    'access_key'
);

try {  
    $client->getApi('issue')->show($issueId);

    if ($client->getLastResponseStatusCode() >= 400 ) {
        throw new \Exception('Error Processing Request', $client->getLastResponseStatusCode());
    }
} catch (\Psr\Http\Client\RequestExceptionInterface $e) {
    // Exception for when a request failed.
} catch (\Psr\Http\Client\NetworkExceptionInterface $e) {
    // Thrown when the request cannot be completed because of network issues.
} catch (\Exception $e) {
    // Thrown when the response status code is 404, 500, etc.
}
```
