### ISSUE TITLE
Updating custom fields in Versions

### ISSUE THREAD

**Issue by michael-delle** [kbsali/php-redmine-api#216]
We can update **issue** custom fields but not **version** custom fields.

Error: SimpleXMLElement::addChild() expects parameter 2 to be string, array given

**Comment by Art4** [comment]
This is possible and with v1.7.0 there is no Error shown. Try it like this:

```php
$client->getApi('version')->update($versionId, [
    'custom_fields' => [
        [
            'id' => 9, // id of the custom field
            'value' => 'foobar',
        ],
    ],
]);
```
