### ISSUE TITLE
can we read comments from the issue?

### ISSUE THREAD

**Issue by manishjaingit** [kbsali/php-redmine-api#217]
I am looking forward to reading comments via Rest API if somebody can help me to read it or guide me about the url of getting comments, so please help..

**Comment by kbsali** [comment]
You should check this on Redmine's doc : http://www.redmine.org/projects/redmine/wiki/Rest_Issues
But it looks like they do not expose this information.

**Comment by kbsali** [comment]
You should check this on Redmine's doc : http://www.redmine.org/projects/redmine/wiki/Rest_Issues
But it looks like they do not expose this information.
