### ISSUE TITLE
\Redmine\Api\Attachment::upload doesn't accept file content as parameter

### ISSUE THREAD

**Issue by zglurb** [kbsali/php-redmine-api#227]
It seems like the behavior of this method changed recently. It used to ask for the file content as a parameter, now it seems to ask for a path?

While debugging to find the issue, I also found an issue in this method :

```
private function isUploadCall($path, $data)
{
    return
        '/uploads.json' === $path ||
        '/uploads.xml' === $path &&
        isset($data) &&
        is_file($data)
    ;
}
```

There should be parentheses around  `'/uploads.json' === $path || '/uploads.xml' === $path`.

As a result, I have this error while trying to call \Redmine\Api\Attachment::upload with a file content :

> \Redmine\Client::prepareUploadRequest line 612 : fopen() expects parameter 1 to be a valid path, string given

**Comment by kbsali** [comment]
@zglurb thanks for reporting, I have applied your proposed solution, let me know if it does indeed fix the issue! :)

**Comment by zglurb** [comment]
Unfortunately, it didn't fix our issue.

It seems like `is_file()` (line 605) doesn't accept strings that aren't valid paths either. I would expect it to just return `false` but it crashes instead. At least when `$data` contains binary like an image.

> is_file() expects parameter 1 to be a valid path, string given

Should I adapt the way I used to call `\Redmine\Api\Attachment::upload` and pass a filename?

**Comment by kbsali** [comment]
sorry for the late answer. I am not using this lib anymore on a daily basis. If you find a work around or can think of a proper fix, please don't hesitate to share your solution (or even better to open a Pull Request! :)).
