### ISSUE TITLE
Composer requirements php7.2

### ISSUE THREAD

**Issue by babiinazar** [kbsali/php-redmine-api#230]
Hello
Why you upgrade composer require php version to 7.0 => 7.2?
If this not critical for you please update composer:
"php": "^5.4 || ^7.2" => "php": "^5.4 || ~7.3"

Thank you!

**Comment by orlitzky** [comment]
We're up to php-8.x now. Please also support a modern version of PHPUnit. The latest supported phpunit-6.0 is several years old, out of support, and broken with newer versions of PHP itself.

**Comment by Art4** [comment]
In a next release there will be PHP 7.4 required. 

@kbsali I think, this can be closed.

**Comment by kbsali** [comment]
thanks @Art4 
The issues definitely need some attention! :grimacing:

**Comment by Art4** [comment]
> thanks @Art4
> The issues definitely need some attention! 😬

If you like you can give me the rights for triage and tag the issues.
