### ISSUE TITLE
Get issue id in response to creating a new issue

### ISSUE THREAD

**Issue by shuniada** [kbsali/php-redmine-api#232]
When creating an issue via API how can I get id of that issue?

**Comment by kbsali** [comment]
It seems you cannot get it from the POST call : http://www.redmine.org/projects/redmine/wiki/Rest_Issues

So you might want to directly do a GET /issues right after your POST

And I'm sorry but I have not time to work on this project anymore. I might ask the little community of active users to maintain it.

**Comment by Art4** [comment]
You can read the ID from the response.

```php
$return = $client->getApi('issue')->create([
    'project_id' => $projectId,
    'subject' => 'Issue Subject',
]);

if ($return instanceof \SimpleXMLElement) {
    var_dump($return->id->__toString()); // returns the ID of the new issue, e.g. "19"
}
```
