### ISSUE TITLE
Create time entry fails due simplexml entity error

### ISSUE THREAD

**Issue by Detzler** [kbsali/php-redmine-api#233]
Can not create/update a time entry which contains xml entities in comments field:

```
$client->time_entry->create([
    'issue_id' => $id,
    'spent_on' => $spentOn,
    'hours' => $hours,
    'activity_id' => $activityId,
    'comments' => 'some text with xml entities: & < > '
]);
```

`SimpleXMLElement::addChild(): unterminated entity reference`

**Comment by kbsali** [comment]
@Detzler , you hopefully found a work around your issue back in ... 2019 :grimacing: 
but thanks to @Art4 it is now fixed! :tada:

**Comment by Art4** [comment]
A workaround would be to use `htmlspecialchars()` on the input before set them to `->create()`.
