### ISSUE TITLE
Read an issue notes

### ISSUE THREAD

**Issue by rodskin** [kbsali/php-redmine-api#238]
Is there a way to get notes (public and private) for each issue and who posted them? 
like 
``` $issue = $client->api('issue')->show($issueId, array('include' => 'notes'));```

**Comment by rodskin** [comment]
auto answering: 
can be found in 
$issue = $client->api('issue')->show($ticket['id'], array('include' => 'journals'));

**Comment by kbsali** [comment]
@rodskin i'll go ahead and close the issue then! :)
