### ISSUE TITLE
Update README.markdown. assigned_to should be assigned_to_id

### ISSUE THREAD

**Issue by sscotter** [kbsali/php-redmine-api#245]
Hi,

I've been struggling to get issues assigned to users or groups using the example in README.markdown

~~~
$client->issue->create([
    'project_id'  => 'test',
    'subject'     => 'some subject',
    'description' => 'a long description blablabla',
    'assigned_to' => 'user1',
]);
~~~

The issue is created but the the assignee is unpopulated. 

I checked the Redmine documentation at https://www.redmine.org/projects/redmine/wiki/Rest_Issues and noticed they're saying use assigned_to_id.

I looked at the history (https://www.redmine.org/projects/redmine/wiki/Rest_Issues/history?page=1) and can see that it changed at some point, not exactly sure when.., but around 2010 time.

Thanks for the code 👍 

Cheers

Steve

**Comment by kbsali** [comment]
ok, interesting. As you may have realized checking the history, this project is not actively maintained anymore,
maybe we could simply send both parameters

**Comment by kbsali** [comment]
I just double checked the code, and `assigned_to` gets converted to `'assigned_to_id', so if the username you used is correct, it should have worked.
I have updated the docs to make it clearer that both options work
