### ISSUE TITLE
Debian Installation - Unable to locate package monitoring-to-redmine-notify

### ISSUE THREAD

**Issue by bipinraut** [kbsali/php-redmine-api#247]
Debian Installation giving problem :
Please check below logs 

**wget -O - http://v.s.cz/info@vitexsoftware.cz.gpg.key|sudo apt-key add -**

--2020-09-13 15:22:43--  http://v.s.cz/info@vitexsoftware.cz.gpg.key
Resolving v.s.cz (v.s.cz)... 213.151.89.97, 2001:4de8:f001::d32
Connecting to v.s.cz (v.s.cz)|213.151.89.97|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-13 15:22:43 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.

**apt update**

Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                               
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease                                                                                                 
Get:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                                                  
Hit:5 http://ppa.launchpad.net/gluster/glusterfs-7/ubuntu bionic InRelease          
Get:6 http://us.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:7 http://v.s.cz stable InRelease                         
Err:8 http://v.s.cz stable Release                 
  404  Not Found [IP: 213.151.89.97 80]
Reading package lists... Done                      
E: The repository 'http://v.s.cz stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**My OS version is** 

cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by kbsali** [comment]
sorry, I'm not aware of a deb package available for this lib, but if there is one you should contact its maintainer

**Comment by bipinraut** [comment]
Thank you very much for responding, i have manage to install via manual installation, but now i am having other problem, 
inside service-notify-redmine.php i see only Icinga\Notifier nothing for nagios how do i configure this script for nations ?
when i am running this script it says below logs 
 $> php service-notify-redmine.php
Set ICINGA_CONTACTADDRESS1 enviroment variable to Redmine URL  http://nagiosintegrator@10.3.13.89:8090?project=nagios-tickets
