### ISSUE TITLE
Add watcher_user_id

### ISSUE THREAD

**Issue by phungthuan99** [kbsali/php-redmine-api#288]
I want to add watcher_user_id, what should I do?
and i tried using this function inside file Redmine/Api/Issue.php but it doesn't work
`public function addWatcher($id, $watcherUserId)
{
return $this->post('/issues/'.$id.'/watchers.xml', '<user_id>'.$watcherUserId.'</user_id>');
}`
my code
`$client->getApi('issue')->addWatcher($issue_id,$watcher_user_id);`
thanks

**Comment by Art4** [comment]
Please try this: (untested)

```php
$client->getApi('issue')->update($issueId, [
    'watcher_user_ids' => [
        $watcher_user_id
    ],
]);
```

**Comment by phungthuan99** [comment]
> Please try this: (untested)
> 
> ```
> $client->getApi('issue')->update($issueId, [
>     'watcher_user_ids' => [
>         $watcher_user_id
>     ],
> ]);
> ```
Thanks, But I tried it but it still doesn't work
:((

**Comment by phungthuan99** [comment]
> > Please try this: (untested)
> > ```
> > $client->getApi('issue')->update($issueId, [
> >     'watcher_user_ids' => [
> >         $watcher_user_id
> >     ],
> > ]);
> > ```
> 
> Thanks, But I tried it but it still doesn't work
> :((

this is my code, can you check it for me
$issue_id = $_REQUEST['issue_id']; 
        $id_user_watcher = $_REQUEST['id_user_watcher'];
        $client->getApi('issue')->update($issue_id, [
            'watcher_user_ids' => [
                $id_user_watcher
            ],
        ]);
I console.log it still get working and value, but after execute getApi it gives error

**Comment by Art4** [comment]
The [Redmine docs](https://www.redmine.org/projects/redmine/wiki/Rest_Issues#Adding-a-watcher) tells:

> ## Adding a watcher
> 
> _Added in 2.3.0_
> 
> `POST /issues/[id]/watchers.[format]`
> 
> Parameters:
> 
>- `user_id` (required): id of the user to add as a watcher

But for me it is unclear how to set the required `user_id`. Could someone help me?

**Comment by Art4** [comment]
Hey @phungthuan99, I just tested adding a watcher to an issue with this code:

```php
$client->getApi('issue')->addWatcher($issueId, $userId);
```

The code works as expected. Please make sure that 

- the `$issueId` and `$userId` are correct
- the user has the permission to watch the issue
- you are using Redmine 2.3 or newer
