### ISSUE TITLE
Possible to get all issues (open and closed)

### ISSUE THREAD

**Issue by Top-CMS** [kbsali/php-redmine-api#290]
Hi,

With the default settings I get all issues with status open
or when 'status_id' => 'closed', I get closed issues, butI want them all

How can I do that?
```
$client->getApi('issue')->all([
		'limit' => 500,
		//'status_id' => 'open',
		//'status_id' => 'closed',
		'sort' => 'id'
	]);
```

**Comment by Top-CMS** [comment]
Found it:
```
$client->getApi('issue')->all([
		'limit' => 500,
		'status_id' => '*',
		'sort' => 'id'
	]);
```

Now finding solution with date start_date from to
from
`'start_date' => '2021-01-01',`
To
`'start_date' => '2021-01-31',`

**Comment by Art4** [comment]
Hey, please take a look at the [Redmine API documentation](https://www.redmine.org/projects/redmine/wiki/Rest_Issues#Listing-issues). 

So try this:
```php
$data = $client->getApi('issue')->all([
    'start_date' => '><2020-01-01|2021-01-31',
]);
```

**Comment by Top-CMS** [comment]
Top, thnx, that works great
