### ISSUE TITLE
Searching issues by subject with wildcard not working

### ISSUE THREAD

**Issue by italo1983** [kbsali/php-redmine-api#292]
Searching issues by subject using wildcard does not return results:

```
$data = [
                'offset' => $offset,
                'limit' => $limit,
                'sort' => $sort,
                'project_id' => $project_id,
                'tracker_id' => $tracker_id,
                'status_id' => $status_id,
                'subject' => '~'.$subject
 ];

$res = $this->redmine->getApi('issue')->all($data);
```

**Comment by Art4** [comment]
Hey 👋 

I simplified your example to just the wildcard field in the subject:

```php
$res = $client->getApi('issue')->all([
    'subject' => '~Issue'
]);
```

This gives me 4 results and thats the number I'd expected.

Please make sure that your other values in `$data` are correct.

**Comment by italo1983** [comment]
Hi,
sorry but is not working..
<img width="467" alt="Schermata 2021-10-05 alle 00 39 17" src="https://user-images.githubusercontent.com/14132969/135934140-a6c4c46a-b9b6-40f3-813d-48b8647810a0.png">
<img width="493" alt="Schermata 2021-10-05 alle 00 39 37" src="https://user-images.githubusercontent.com/14132969/135934149-b7499957-5e32-4ce7-8d3e-cbfba85e1af3.png">

**Comment by Art4** [comment]
Please try `2016curry~`.

But this is an undocumented feature of Redmine-API. It seems that using wildcards in subject isn't supported at the moment, see https://www.redmine.org/issues/13347

So there is nothing we can do here.
