### ISSUE TITLE
Installation with Composer not working

### ISSUE THREAD

**Issue by andreasGothe** [kbsali/php-redmine-api#312]
Hi, when I try to install with composer this is what I get:

```
 [RuntimeException]
 No composer.json present in the current directory (./composer.json), this may be the cause of the following exception.

[InvalidArgumentException]
Could not find a matching version of package kbsali/php-redmine-api. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

Any suggestions? Thanks for the help!

**Comment by Art4** [comment]
Hey 👋 

Could you please post the full command you are using to install the library?

**Comment by Art4** [comment]
Also please make sure to use the correct package name `kbsali/redmine-api`, not `kbsali/php-redmine-api`

**Comment by kbsali** [comment]
> Also please make sure to use the correct package name kbsali/redmine-api, not kbsali/php-redmine-api

that's indeed probably the issue! :)

**Comment by andreasGothe** [comment]
Thanks for your quick help! This was indeed the problem! Seem like the usage.md needs to be corrected:

https://github.com/kbsali/php-redmine-api/blob/v2.2.0/docs/usage.md

I copied it from there and got 'php-redmine-api' :)

**Comment by Art4** [comment]
@andreasGothe Thank you very much for pointing this out. 😊
