### ISSUE TITLE
 author_id Params Not Working When Creating New Issue

### ISSUE THREAD

**Issue by maniicandy** [kbsali/php-redmine-api#400]
It created an issue with the user's ID that authenticates with the API. (**author_id params not working**)
 
 This is my request 
 
```
 $response = $client->getApi('issue')->create([
    'project_id' => 'Test',
    'subject' => 'test from API',
    'description' => 'test api',   
	'author_id' => '12',
    'watcher_user_ids' => [],
]);
```

**Comment by Art4** [comment]
There is no `author_id` parameter for creating an issue, see https://www.redmine.org/projects/redmine/wiki/Rest_Issues#Creating-an-issue

The author of the issue will always be the owner of the apikey. If the owner of the apikey has admin priviliges you can use [user impersonation](https://github.com/kbsali/php-redmine-api/blob/v2.x/docs/usage.md#impersonate-user) (see also [Redmine docs](https://www.redmine.org/projects/redmine/wiki/Rest_api#User-Impersonation)) to create an issue on behalf of another user.

```php
$client->startImpersonateUser('kim'); // username of user with id 12
// all requests will now impersonate the user `kim`

$response = $client->getApi('issue')->create([
    'project_id' => 'Test',
    'subject' => 'test from API',
    'description' => 'test api',   
    'watcher_user_ids' => [],
]);

// To stop impersonation
$client->stopImpersonateUser();
```
