### ISSUE TITLE
Attachment on issue failed

### ISSUE THREAD

**Issue by foxpowa** [kbsali/php-redmine-api#45]
<pre>
$upload = json_decode( $client->api('attachment')->upload(file_get_contents('feedback.png')));

$issue = $client->api('issue')->create(array(
    'project_id'  => '3',
    'subject'     => 'Feedback',
    'description' => "desc"
));

$client->api('issue')->attach($issue->id, array(
    'token'        => $upload->upload->token,
    'description'  => 'Attachement',
    'content_type' => 'image/png'
));
</pre>
$upload is null, and thus, issue have no attachment.

feedback.png is ok.
I've also tried with

<pre>
$upload = json_decode( $client->api('attachment')->upload(base64_decode($img)))
</pre>
(where $img is a base64 encode image, of course)
which IS an octet-stream, but it failed too.

Thks for any idea...

**Comment by kbsali** [comment]
@foxpowa closing as this is veeeeeeery old, ok?

**Comment by foxpowa** [comment]
Fine ;)
