### ISSUE TITLE
Find a project, limit 25

### ISSUE THREAD

**Issue by VoidAndAny** [kbsali/php-redmine-api#46]
When I search a project with getIdByName, my projects are not found if they are not in the 25 first one.

Indeed "getIdByName" call "listing" function to construct an array of projects.
"Listing" call "all" function because $this->projects is empty and finally "all" function call "retrieveAll" function of AbstractApi.

The problem is that "retrieveAll" function has a default limitation of 25 items so if my project isn't in the first 25 ones it isn't found.

The only way I found for the moment is to call "all" function with a big limit value (200 as I have 160 projects) before calling getIdByName.
But I will need to change this value when I will have more than 200 projects.

Any advice ?

**Comment by Henry31** [comment]
As a workaround i check the output against my limit.
```
if ($project['total_count'][0] >= $project_limit) {
  //warning
}
```

**Comment by ferdynator** [comment]
I've changed the `AbstractApi::retrieveAll` method to work around this:

    protected function retrieveAll($endpoint, array $params = array())
    {
        $defaults = array(
            'limit' => 100,
            'offset' => 0,
        );
        $params = $this->sanitizeParams($defaults, $params);

        $ret = array();

        $limit = $params['limit'];
        $offset = $params['offset'];
        $totalCount = 101;

        while ($offset < $totalCount) {

            $newDataSet = (array) $this->get($endpoint.'?'.http_build_query($params));
            $ret = array_merge_recursive($ret, $newDataSet);

            if (empty($newDataSet) || !isset($newDataSet['limit']) || !isset($newDataSet['total_count'])) {
                $totalCount = 0;
            } else {
                $totalCount = $newDataSet['total_count'];
                $offset += $limit;
                $params['offset'] = $offset;
            }
        }

        return $ret;
    }

This solves the issue but many tests fail. Can anyone confirm my solution? If it works for you I will update the tests correctly and create a PR

**Comment by kbsali** [comment]
@VoidAndAny, it's been a loooong time since you raised this issue... see @ferdynator 's last comment, should this still be needful to you!

**Comment by Detzler** [comment]
retrieveAll says: "Retrieves all the elements of a given endpoint (even if the total number of elements is greater than 100)."

It doesn't do what it should. Please fix
