### ISSUE TITLE
SimpleXMLElement::addChild(): unterminated entity reference

### ISSUE THREAD

**Issue by MichaelKling** [kbsali/php-redmine-api#54]
Writing a small import script for issues i experienced this error.

It happened when one of the issues had an & inside the description.
"http://www.exmple.org/blapage.aspx?PfId=415616&OtherId=231245&SomeOtherId=1&pref=plqv#.Ug5xIFJAeXE"

and it seems to be this problem:
http://stackoverflow.com/questions/17027043/unterminated-entity-reference-php

I could solve it by changing Issue.php line 90 from:
$xml->addChild($k, $v );
into
$xml->addChild($k);
$xml->$k = $v;

anyway that was just quickfix and we need to decide if this should be done on all XML creation methods or if the user needs to escape the data accordingly before inserting it into the redmine api (in that case it should be documented somewhere)

**Comment by vikaschauhan1** [comment]
Just use htmlspecialchars in secod parameter i.e
replace $xml->addChild($k, $v ) with $xml->addChild($k, htmlspecialchars($v) );
