### ISSUE TITLE
Make limit optional

### ISSUE THREAD

**Issue by JanMalte** [kbsali/php-redmine-api#61]
I think it would be better, if the limit is provided optional and default is set to no limit. 
This would solve #46 too.

If you accept this issue, I can try to provide a PR with the needed changes. Just tell me if this should be implemented or not.

**Comment by ferdynator** [comment]
Checkout my [solution here](https://github.com/kbsali/php-redmine-api/issues/46#issuecomment-109272166). Please confirm if it works for you
