### ISSUE TITLE
Ticket creation - Start_date problem

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#94]
If i create a ticket, and i don´t want a start_date it isn´t possible. It replaced the empty "start_date" with the currently date from today.

example:
```
$client->api('issue')->create(array(
							'project_id'  => $project_id,
							'subject'     => $array_ticket['subject'],
							'description' => $array_ticket['description'],
							'assigned_to_id' => $array_ticket['assigned_to']['id'], 
							'status_id' => $array_ticket['status']['id'],
							'priority_id' => $array_ticket['priority']['id'],
							'tracker_id' => $array_ticket['tracker']['id'],
							'category_id' => $new_category_id,
							'start_date' => null);
```
if i didn´t set the start_date it will also not work.

and something like `none` or `0` does not work, too.

Can you help me?

**Comment by JanMalte** [comment]
Is an empty start date supported by Redmine itself?
What happens if you create a Ticket directly in Redmine and leave the start_date field empty? Will it be replaced with the current datetime?

**Comment by Henry31** [comment]
yes it will replaced with the current datetime :(

**Comment by Art4** [comment]
@Henry31 There is a setting for this behaviour in Administration -> Settings -> Issues -> "Use current date as start date for new issues". Uncheck this setting and "start_date" won't be replaced with the current date.

**Comment by Henry31** [comment]
Oh, i see! Thanks a lot! I think now it must work!

If not i will reopen this issue.

Thanks a lot @Art4

**Comment by kbsali** [comment]
thx @Henry31 !
