### ISSUE TITLE
How set the option“inherited members” for projects

### ISSUE THREAD

**Issue by Henry31** [kbsali/php-redmine-api#95]
I create automatically with the rest api a lot of projects in Redmine.

But we have the problem that for every project we need to set manually the option "inherited members from parent projects" (i don´t know exactly the right spelling). This is very disappointing.

This is the snippet how we create a project:

``` php
$client->api('project')->create(array(
                'name'     => $project_name,
                'identifier' => $project_identifier,
                'tracker_ids' => $tracker_ids,
                'parent_id' => $produktions_projekt_id));
```

This work´s nicely. But i want to add something like this:

``` php
'inherited members' => true
'inherited members' => 1
'inherited members' => '1'
```

I tried these three options, but they didn´t worked. I hope someone of you can help me with this problem?

Thanks a lot!

I reported it also here: http://stackoverflow.com/questions/27148877/how-set-the-optioninherited-members-for-projects-with-the-rest-api-from-redmin

**Comment by Henry31** [comment]
Thanks a lot for your fast response.

I open a issue on redmine.org today --> http://www.redmine.org/issues/19214

**Comment by LucileQ** [comment]
Hi,

I've updated Redmine's wiki (inherit_members and a few other fields added).
Redmine does support inherit_members since inherit_members implementation. (fev 2013 ~ version 2.3.0)

For development purpose you should refer to the source code and its tests.

**Comment by Henry31** [comment]
@kbsali have you notice this change? i couldn´t open this issue anymore.

**Comment by kbsali** [comment]
I'm not sure i understand you question @Henry31

**Comment by Henry31** [comment]
@kbsali you said "this is not supported through the api" but it is supported as you can see here: http://www.redmine.org/projects/redmine/wiki/Rest_Projects#Creating-a-project
