### ISSUE TITLE
Guzzle support

### ISSUE THREAD

**Issue by funivan** [kbsali/php-redmine-api#97]
Hi. I see guzzle support in current todo list.
I can do that, but i think there is some backward incompatibles.

I will show you my vision of new API 

```php
 $httpClient = new \GuzzleHttp\Client([
        'base_url' => 'http://redmine.example.com',
        'defaults' => [
          'auth' => ['michael', 'test']
        ]
  ]);

$client = new \Redmine\Client($httpClient);
# standard api call will not change
$client->api('tracker')->all();

``` 
With this aproach we can move all http configuration and loggin (authorization, base url  ) to `Client`

Or  there is second way

```php
$httpClient = new \Redmine\HttpClient(); // extends \GuzzleHttp\Client
$httpClient->setBaseUrl('http://redmine.example.com');

$httpClient->setApiKey('jfki478jrba408745'); 
// or 
$httpClient->setUserNameAndPassword('dev_user', '457ffDA'); 

# next code is similar
$client = new \Redmine\Client($httpClient);
# standard api call will not change
$client->api('tracker')->all();

```
At this point `Redmine\Client::runRequest` create request, execute it via guzzle client and get response.

**Comment by kbsali** [comment]
Hi @funivan,

thanks for clearly detailing your ideas, but i would leave this aside for now : 
* nobody really asked for it,
* i originally thought that guzzle would make it easier to test the library, but @JanMalte made an amazing job at testing it all without adding any dependency,
* and recently @orlitzky proposed to package php-redmine-api on Gentoo, and to do so we should again keep the dependencies to a minimum.

So, unless this brings a real benefit apart from code style, i would leave it as it is.

What do you think?

**Comment by funivan** [comment]
@kbsali i have troubles with authorisation (specific in our development server) I already said about that #63 Guzzle support is only one way to solve that. 

I understand that for one user it is not good to break out api and rewrite library.

My position. If several users vote for guzzle support we can implement it.
You can close this issue and refer  to it from Readme (Maybe Guzzle for handling http connections vote here #97)

**Comment by kbsali** [comment]
@funivan how about you describe exactly have you fixed your problem and we document it or refer to it in the readme?

thx!

**Comment by funivan** [comment]
My solution is not very good at current point https://github.com/funivan/redmine-api/blob/master/src/Fiv/Redmine/Client.php#L99:L107 but it works. 
That's why i want to rewrite it with guzzle client)

**Comment by JanMalte** [comment]
Would this changed ```Client.php``` solve the problem of having tweo authntification modes at once?
https://gist.github.com/JanMalte/59ac16355028a3b8d54b

You can have a username and password and/or an API key.

The gist was just scribbled down in a few seconds as an idea of having both mechanisms at the same time.

**Comment by funivan** [comment]
@JanMalte  i think yes. This solution allow users two method authentication.

**Comment by gpilla** [comment]
I think that one of the benefits, can be the implementation of the guzzle cache.

**Comment by ferdynator** [comment]
> So, unless this brings a real benefit apart from code style, i would leave it as it is.

It would be simple to add a nice [caching layer](http://guzzle3.readthedocs.org/plugins/cache-plugin.html). Running many requests to this  API (maybe even asynchronous) can be rather slow and a caching layer would definitely help in my case.

**Comment by funivan** [comment]
@ferdynator  agree. Sometimes cache is very useful

**Comment by kbsali** [comment]
True, although implementing a cheap caching layer on top of what we already have should be rather easy.
Having said that, if someone wants to submit a PR for supporting the current curl client AND Guzzle, that would be awesome.

**Comment by funivan** [comment]
@JanMalte i solve issue with 2 authorization methods and all workds fine =) 
```php
$client = new \Redmine\Client('http://username:password@redmine.domain.com', 'apikey');
$client->setUseHttpAuth(false);
```

**Comment by funivan** [comment]
Closing due to the timeout.
