### ISSUE TITLE
Add support for scrutinizer-ci.com

### ISSUE THREAD

**Issue by JanMalte** [kbsali/php-redmine-api#98]
It would suggest to let scrutinizer-ci.com check the code for each commit:
https://scrutinizer-ci.com/

It accepted, I can commit a basic configuration file for it. All you have to do is set up the account on scrutinizer-ci.com as this is your repository. ;)

**Comment by kbsali** [comment]
Thanks! I've just signed up and... wow that's pretty awesome! :)
Here is the 1st report : https://scrutinizer-ci.com/g/kbsali/php-redmine-api/inspections/7eab3e7a-0f30-40ab-8bca-63c77e461864

Good! There room for improvement! :) Please don't hesitate to commit a configuration file!
thx

**Comment by JanMalte** [comment]
Yes, i just started using the tool for another project. Sadly it contains only functions, which aren't rated by scrutinizer-ci.com as it is designed for OOP. But the checks gives already a very clear view over the state of a project.

I just added the external code coverage for it. Some more configuration will come later in a new PR.

**Comment by kbsali** [comment]
mind blown! Thanks a lot (AGAIN!) @JanMalte !!! :+1: :+1:
