### ISSUE TITLE
Add support for travis-ci.com

### ISSUE THREAD

**Issue by JanMalte** [kbsali/php-redmine-api#99]
It would suggest to let travis-ci.com run the tests for each commit:
https://travis-ci.org/

It accepted, I can commit a basic configuration file for it. All you have to do is set up the account on travis-ci.com as this is your repository. ;)

**Comment by kbsali** [comment]
i integrated travis-ci a few months ago, is there anything we could improve?
-> https://github.com/kbsali/php-redmine-api/blob/master/.travis.yml

**Comment by JanMalte** [comment]
I create a PR with the changes. Pushing the coverage to scrutinizer-ci.com was added.

This issue can be closed, if the PR is merged.

**Comment by kbsali** [comment]
:+1: great!
